version: '2.2'
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - esdata1:/usr/share/elk/data
    network_mode: "host"

  web:
    build: .
    command: node server.js
    volumes:
      - .:/usr/app/es/
      - /user/app/es/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - elk
    # networks:
    #   - esnet
    network_mode: "host"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
  #   container_name: elasticsearch
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata1:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - esnet
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   # networks:
  #   #   - esnet
  #   network_mode: "host"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
